complete_task:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: task

reset_task:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: task
